server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: gabilimajk12U
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate: 
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: gabilimajk12U
    locations:
    - classpath:/db
    enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non-null